add cars_list db,  show: table, pagination
ViktorBurchenia/rails_cars_management pull request #2
Opened 2023-02-16 12:00 UTC by ViktorBurchenia

2023-02-20 17:22 UTC, AsakuraRET requested changes

2023-02-20 17:22 UTC, AsakuraRET commented on app/assets/stylesheets/application.scss
> +@import 'search'
Add new line please

2023-02-20 17:22 UTC, AsakuraRET commented on app/assets/stylesheets/search.scss
> +
Add new line please for end file

2023-02-20 17:22 UTC, AsakuraRET commented on app/controllers/cars_controller.rb
> +}
Please add .freeze for constant

2023-02-20 17:22 UTC, AsakuraRET commented on app/controllers/cars_controller.rb
> +    @cars = @cars.order(**SORTING[params[:sort_by]]) if params[:sort_by].present?
Please use private def for this sorting and then use
def_name if params[:sort_by].present?

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/cars/index.html.erb
> +    <%=f.submit 'New car'%>
Please add whitespace

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/cars/index.html.erb
> +<div>
Add newline

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/cars/index.html.erb
> +<%= paginate @cars %>
Please add whitespace

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/cars/new.html.erb
> +    <% end %>
Please remove whitespace

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/search/search_car.html.erb
> +
Remove unused lines

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/search/search_car.html.erb
> +                <th scope="col">model</th>
Please align nesting, use 2 spaces or 1 tab

2023-02-20 17:22 UTC, AsakuraRET commented on app/views/search/search_car.html.erb
> +<% end %>
Please add newline to end file

2023-02-20 17:30 UTC, ViktorBurchenia commented on app/controllers/cars_controller.rb
> +}
fixed

2023-02-20 17:32 UTC, ViktorBurchenia commented on app/views/cars/index.html.erb
> +<div>
fixed

2023-02-20 17:32 UTC, ViktorBurchenia commented on app/views/cars/index.html.erb
> +<%= paginate @cars %>
fixed

2023-02-20 17:33 UTC, ViktorBurchenia commented on app/views/cars/index.html.erb
> +    <%=f.submit 'New car'%>
Fixed

2023-02-20 17:33 UTC, ViktorBurchenia commented on app/assets/stylesheets/application.scss
> +@import 'search'
Fixed

2023-02-20 17:34 UTC, ViktorBurchenia commented on app/assets/stylesheets/search.scss
> +
Fixed

2023-02-20 17:36 UTC, ViktorBurchenia commented on app/views/cars/new.html.erb
> +    <% end %>
Fixed

2023-02-20 17:37 UTC, ViktorBurchenia commented on app/views/search/search_car.html.erb
> +<% end %>
Fixed

2023-02-20 17:43 UTC, ViktorBurchenia commented on app/views/search/search_car.html.erb
> +                <th scope="col">model</th>
Fixed

2023-02-20 17:44 UTC, ViktorBurchenia commented on app/views/search/search_car.html.erb
> +
Fixed

2023-02-23 17:05 UTC, AsakuraRET approved these changes

2023-02-23 17:06 UTC, merged